---
Name: auth0
After:
  - '#coresecurity'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: '%$MaximeRainville\Auth0\Authenticator'
  SilverStripe\Security\MemberAuthenticator\MemberAuthenticator:
    class:
      MaximeRainville\Auth0\Authenticator
